"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { createMediaAsset, type MediaAsset, type MediaCategory, type MediaStatus } from "@/lib/media";
import { readMediaStore, writeMediaStore } from "@/lib/media-store";
import "../admin.css";

export default function MediaAdmin() {
  const [items, setItems] = useState<MediaAsset[]>(readMediaStore);
  const [statusFilter, setStatusFilter] = useState<MediaStatus | "all">("all");
  const [categoryFilter, setCategoryFilter] = useState<MediaCategory | "all">("all");
  const [query, setQuery] = useState("");
  const visible = useMemo(() => items.filter((item) => (statusFilter === "all" || item.status === statusFilter) && (categoryFilter === "all" || item.category === categoryFilter) && `${item.title} ${item.alt}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => a.sortOrder - b.sortOrder), [items, statusFilter, categoryFilter, query]);
  function persist(next: MediaAsset[]) { setItems(next); writeMediaStore(next); }
  function addAsset() { const title = window.prompt("Media title"); const src = window.prompt("Image path or URL"); const alt = window.prompt("Accessible alt text"); if (!title?.trim() || !src?.trim() || !alt?.trim()) return; const next = [...items, { ...createMediaAsset({ title: title.trim(), src: src.trim(), alt: alt.trim(), category: "spaces" }), sortOrder: items.length + 1 }]; persist(next); }
  function patch(id: string, patch: Partial<MediaAsset>) { persist(items.map((item) => item.id === id ? { ...item, ...patch, updatedAt: new Date().toISOString() } : item)); }
  return <main className="adminShell"><aside className="adminSide"><Link className="adminBrand" href="/admin">MERIDIAN <span>SKY</span></Link><p className="adminLabel">MEDIA LIBRARY</p><Link href="/admin" className="backLink">← Control room</Link></aside><section className="adminMain"><header className="adminHeader"><div><p className="adminLabel">ASSET MANAGEMENT</p><h1>Gallery Media</h1></div><button className="adminPrimary" onClick={addAsset}>+ Add media</button></header><div className="adminToolbar"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search media…" aria-label="Search media" /><select value={categoryFilter} onChange={(e) => setCategoryFilter(e.target.value as MediaCategory | "all")}><option value="all">All categories</option><option value="spaces">Spaces</option><option value="views">Views</option><option value="lifestyle">Lifestyle</option><option value="events">Events</option><option value="experience">Experience</option></select><select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value as MediaStatus | "all")}><option value="all">All status</option><option value="published">Published</option><option value="draft">Draft</option><option value="archived">Archived</option></select></div><div className="mediaAdminGrid">{visible.map((item) => <article className="mediaAdminCard" key={item.id}><div className="mediaThumb"><img src={item.src} alt={item.alt} /><span>{item.status}</span></div><div className="mediaAdminBody"><strong>{item.title}</strong><small>{item.alt}</small><div className="mediaAdminControls"><select value={item.category} onChange={(e) => patch(item.id, { category: e.target.value as MediaCategory })}><option value="spaces">Spaces</option><option value="views">Views</option><option value="lifestyle">Lifestyle</option><option value="events">Events</option><option value="experience">Experience</option></select><button onClick={() => patch(item.id, { featured: !item.featured })}>{item.featured ? "★ Featured" : "☆ Feature"}</button><select value={item.status} onChange={(e) => patch(item.id, { status: e.target.value as MediaStatus })}><option value="published">Published</option><option value="draft">Draft</option><option value="archived">Archived</option></select></div></div></article>)}</div></section></main>;
}
