"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import AdminEditPanel, { type EditableContent } from "@/components/AdminEditPanel";
import { readAdminStore, writeAdminStore, type AdminRecord } from "@/lib/admin-store";
import "../admin.css";

const seed: EditableContent[] = [
 {title:"Private Dining",slug:"private-dining",eyebrow:"MERIDIAN EXPERIENCE",description:"A considered dining experience shaped around your people, your occasion and the atmosphere you want to create.",status:"published"},
 {title:"Rooftop Evenings",slug:"rooftop-evenings",eyebrow:"MERIDIAN EXPERIENCE",description:"Let the city become part of the room as the evening moves from cocktails and conversation into the night.",status:"published"},
 {title:"Skyline Friday",slug:"skyline-friday",eyebrow:"SKY SOCIAL",description:"A late-evening social above the city, with music, cocktails and a view that carries the night.",status:"published"}
];
function loadContent(){const store=readAdminStore();const saved=store.experiences.filter(r=>r.contentType==="editorial") as AdminRecord[];return saved.length?saved.map(r=>({title:String(r.title),slug:String(r.slug||""),eyebrow:String(r.eyebrow||"MERIDIAN"),description:String(r.description||""),status:(r.status==="archived"?"archived":r.status==="draft"?"draft":"published") as EditableContent["status"]})):seed}
export default function ContentAdmin(){const [items,setItems]=useState(loadContent);const [selected,setSelected]=useState(0);const [saved,setSaved]=useState(false);const current=items[selected]||items[0];const save=(value:EditableContent)=>{const store=readAdminStore();const existing=store.experiences.findIndex(r=>r.contentType==="editorial"&&r.slug===value.slug);const record:AdminRecord={id:existing>=0?store.experiences[existing].id:`editorial-${Date.now()}`,title:value.title,status:value.status,updatedAt:new Date().toISOString(),contentType:"editorial",slug:value.slug,eyebrow:value.eyebrow,description:value.description};const experiences=[...store.experiences];if(existing>=0)experiences[existing]=record;else experiences.push(record);writeAdminStore({...store,experiences});const next=items.map((item,index)=>index===selected?value:item);setItems(next);setSaved(true);window.setTimeout(()=>setSaved(false),1800)};return <main className="adminShell"><aside className="adminSide"><Link className="adminBrand" href="/admin">MERIDIAN <span>SKY</span></Link><p className="adminLabel">CONTENT STUDIO</p><Link href="/admin" className="backLink">← Control room</Link></aside><section className="adminMain"><header className="adminHeader"><div><p className="adminLabel">EDITORIAL CMS</p><h1>Content Studio</h1></div>{saved&&<span className="saveNotice">Saved locally</span>}</header><div className="contentStudio"><div className="contentList">{items.map((item,index)=><button key={item.slug} className={selected===index?"selected":""} onClick={()=>setSelected(index)}><span>{String(index+1).padStart(2,"0")}</span><strong>{item.title}</strong><small>{item.status}</small></button>)}</div>{current&&<AdminEditPanel key={current.slug} initial={current} onSave={save}/>}</div></section></main>}
